name: flutter_in_action_2nd_materials
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flukit: ^3.0.1
  flutter:
    sdk: flutter
  widget_with_codeview: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
    - family: AbrilFatface
      fonts:
        - asset: assets/fonts/AbrilFatface-Regular.ttf
  assets:
    - assets/images/
    # source code
    - lib/ch2_first_app/
    - lib/ch3_basic_widgets/
    - lib/ch4_layout_widgets/
    - lib/ch5_container_widgets/
    - lib/ch6_scrollable_widgets/
